/*
 * This file was automatically generated by EvoSuite
 * Fri Aug 24 12:41:09 GMT 2018
 */

package wheel.asm;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import wheel.asm.AnnotationVisitor;
import wheel.asm.Attribute;
import wheel.asm.ByteVector;
import wheel.asm.ClassReader;
import wheel.asm.ClassWriter;
import wheel.asm.Edge;
import wheel.asm.FieldWriter;
import wheel.asm.Frame;
import wheel.asm.Item;
import wheel.asm.Label;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FieldWriter_ESTest extends FieldWriter_ESTest_scaffolding {

  /**
  //Test case number: 0
  /*Coverage entropy=1.3862943611198906
  */
  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(330);
      classWriter0.newDouble(0.0);
      classWriter0.newClassItem("");
      classWriter0.version = 330;
      classWriter0.addType("Y@!Ob79<)AB10 Om");
      FieldWriter fieldWriter0 = new FieldWriter(classWriter0, 0, "_l8EuPhA`|Q]h", "_l8EuPhA`|Q]h", "<c?ZV0", "<c?ZV0");
      Attribute attribute0 = new Attribute("PFt][$");
      fieldWriter0.visitAttribute(attribute0);
      fieldWriter0.visitEnd();
      // Undeclared exception!
      try { 
        fieldWriter0.getSize();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("wheel.asm.Attribute", e);
      }
  }

  /**
  //Test case number: 1
  /*Coverage entropy=0.5623351446188083
  */
  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(525);
      FieldWriter fieldWriter0 = new FieldWriter(classWriter0, 1480, "eZQmMsLdK3^:[k", "[]", "[]", (Object) null);
      fieldWriter0.visitEnd();
  }

  /**
  //Test case number: 2
  /*Coverage entropy=0.6931471805599453
  */
  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(330);
      classWriter0.newDouble(0.0);
      classWriter0.newClassItem("");
      classWriter0.version = 330;
      FieldWriter fieldWriter0 = new FieldWriter(classWriter0, 1721, "Y@!Ob79<)AB10 Om", "_l8EuPhA`|Q]h", "<c?ZV0", (Object) null);
      AnnotationVisitor annotationVisitor0 = fieldWriter0.visitAnnotation("_l8EuPhA`|Q]h", true);
      classWriter0.newLong(0L);
      FieldWriter fieldWriter1 = null;
      try {
        fieldWriter1 = new FieldWriter(classWriter0, 330, "-Zkh,*zs![(", "wc3wN!JCQ", "_l8EuPhA`|Q]h", annotationVisitor0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // value wheel.asm.AnnotationWriter@e
         //
         verifyException("wheel.asm.ClassWriter", e);
      }
  }

  /**
  //Test case number: 3
  /*Coverage entropy=1.4750763110546947
  */
  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(330);
      classWriter0.newDouble(0.0);
      classWriter0.newClassItem("");
      classWriter0.version = 330;
      classWriter0.addType("Y@!Ob79<)AB10 Om");
      FieldWriter fieldWriter0 = new FieldWriter(classWriter0, 0, "_l8EuPhA`|Q]h", "_l8EuPhA`|Q]h", "<c?ZV0", "<c?ZV0");
      Attribute attribute0 = new Attribute("PFt][$");
      fieldWriter0.visitEnd();
      fieldWriter0.getSize();
      ByteVector byteVector0 = classWriter0.pool;
      fieldWriter0.put(byteVector0);
      fieldWriter0.visitEnd();
      // Undeclared exception!
      try { 
        fieldWriter0.visitAnnotation((String) null, true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  /**
  //Test case number: 4
  /*Coverage entropy=0.9502705392332347
  */
  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(65535);
      ClassWriter classWriter1 = new ClassWriter(1333);
      Object object0 = new Object();
      FieldWriter fieldWriter0 = new FieldWriter(classWriter1, 1, "", "", "a gUWC+7[TgL]", "'GoE");
      FieldWriter fieldWriter1 = fieldWriter0.next;
      FieldWriter fieldWriter2 = classWriter1.firstField;
      fieldWriter2.visitAnnotation("", false);
      fieldWriter0.visitAnnotation("S", false);
      ByteVector byteVector0 = new ByteVector();
      ByteVector byteVector1 = byteVector0.putByte(47);
      fieldWriter0.put(byteVector1);
      assertSame(fieldWriter0, fieldWriter2);
  }

  /**
  //Test case number: 5
  /*Coverage entropy=1.1209503926735833
  */
  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(65535);
      ClassWriter classWriter1 = new ClassWriter(1333);
      Object object0 = new Object();
      FieldWriter fieldWriter0 = new FieldWriter(classWriter1, 1, "", "", "a gUWC+7[TgL]", "'GoE");
      FieldWriter fieldWriter1 = fieldWriter0.next;
      FieldWriter fieldWriter2 = classWriter1.firstField;
      fieldWriter2.visitAnnotation("", false);
      fieldWriter0.visitAnnotation("S", false);
      ByteVector byteVector0 = new ByteVector();
      Attribute attribute0 = new Attribute("!Q>E->T");
      fieldWriter2.visitAttribute(attribute0);
      // Undeclared exception!
      try { 
        fieldWriter0.getSize();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("wheel.asm.Attribute", e);
      }
  }

  /**
  //Test case number: 6
  /*Coverage entropy=1.3667110520552042
  */
  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(330);
      classWriter0.newDouble(0.0);
      classWriter0.newClassItem("");
      classWriter0.version = 330;
      classWriter0.addType("Y@!Ob79<)AB10 Om");
      FieldWriter fieldWriter0 = new FieldWriter(classWriter0, 0, "_l8EuPhA`|Q]h", "_l8EuPhA`|Q]h", "<c?ZV0", "<c?ZV0");
      Attribute attribute0 = new Attribute("PFt][$");
      fieldWriter0.visitAnnotation("", true);
      fieldWriter0.visitAttribute(attribute0);
      fieldWriter0.visitEnd();
      // Undeclared exception!
      try { 
        fieldWriter0.getSize();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("wheel.asm.Attribute", e);
      }
  }

  /**
  //Test case number: 7
  /*Coverage entropy=1.277034259466139
  */
  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(330);
      classWriter0.newDouble(0.0);
      classWriter0.newClassItem("");
      classWriter0.version = 330;
      classWriter0.addType("Synthetic");
      String string0 = "ConstantValue";
      FieldWriter fieldWriter0 = new FieldWriter(classWriter0, (-142), "ConstantValue", "|v.7a", "Y@!Obz9<)ABe0 Fm", "Y@!Obz9<)ABe0 Fm");
      Attribute attribute0 = new Attribute("Synthetic");
      fieldWriter0.visitAttribute(attribute0);
      fieldWriter0.visitEnd();
      // Undeclared exception!
      try { 
        fieldWriter0.getSize();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("wheel.asm.Attribute", e);
      }
  }

  /**
  //Test case number: 8
  /*Coverage entropy=1.2554823251787535
  */
  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(330);
      classWriter0.newDouble(330);
      classWriter0.newClassItem("");
      classWriter0.addType("");
      String string0 = "ConstantValue";
      String string1 = "|v.7a";
      FieldWriter fieldWriter0 = new FieldWriter(classWriter0, (-628), "", "", "|v.7a", "");
      Attribute attribute0 = new Attribute("5HO");
      fieldWriter0.visitAttribute(attribute0);
      fieldWriter0.visitEnd();
      // Undeclared exception!
      try { 
        fieldWriter0.getSize();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("wheel.asm.Attribute", e);
      }
  }

  /**
  //Test case number: 9
  /*Coverage entropy=1.0751393240053735
  */
  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(65535);
      ClassWriter classWriter1 = new ClassWriter(1333);
      Object object0 = new Object();
      FieldWriter fieldWriter0 = new FieldWriter(classWriter1, 1, "", "", "a gUWC+7[TgL]", "'GoE");
      FieldWriter fieldWriter1 = fieldWriter0.next;
      FieldWriter fieldWriter2 = classWriter1.firstField;
      fieldWriter2.visitAnnotation("", false);
      fieldWriter0.visitAnnotation("S", false);
      ByteVector byteVector0 = new ByteVector();
      Attribute attribute0 = new Attribute("!Q>E->T");
      fieldWriter2.visitAttribute(attribute0);
      // Undeclared exception!
      try { 
        fieldWriter0.put(byteVector0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("wheel.asm.Attribute", e);
      }
  }

  /**
  //Test case number: 10
  /*Coverage entropy=-0.0
  */
  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(0);
      String string0 = null;
      Object object0 = new Object();
      FieldWriter fieldWriter0 = null;
      try {
        fieldWriter0 = new FieldWriter(classWriter0, 2, "void", "Co.\"JTn<wG'lC0[#9", (String) null, object0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // value java.lang.Object@153b58ca
         //
         verifyException("wheel.asm.ClassWriter", e);
      }
  }

  /**
  //Test case number: 11
  /*Coverage entropy=1.2148896539491205
  */
  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(65535);
      ClassWriter classWriter1 = new ClassWriter(1333);
      Object object0 = new Object();
      FieldWriter fieldWriter0 = new FieldWriter(classWriter1, 1, "'GoE", "'GoE", "a gUWC+7[TgL]", "'GoE");
      FieldWriter fieldWriter1 = new FieldWriter(classWriter1, 65535, "a gUWC+7[TgL]", "'GoE", "'GoE", "a gUWC+7[TgL]");
      FieldWriter fieldWriter2 = classWriter1.firstField;
      fieldWriter2.getSize();
      fieldWriter0.visitAnnotation("'GoE", true);
      fieldWriter1.visitAnnotation("a gUWC+7[TgL]", true);
      ByteVector byteVector0 = classWriter1.pool;
      fieldWriter1.put(byteVector0);
      ByteVector byteVector1 = new ByteVector();
      byteVector1.putByte(1333);
      fieldWriter1.put(byteVector1);
      int int0 = fieldWriter2.getSize();
      assertEquals(36, int0);
  }

  /**
  //Test case number: 12
  /*Coverage entropy=0.8641502031949702
  */
  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(330);
      Item item0 = classWriter0.key;
      classWriter0.version = 330;
      FieldWriter fieldWriter0 = new FieldWriter(classWriter0, 1184, "Y@!Ob79<)AB10 Om", "Y@!Ob79<)AB10 Om", (String) null, (Object) null);
      FieldWriter fieldWriter1 = fieldWriter0.next;
      FieldWriter fieldWriter2 = classWriter0.firstField;
      FieldWriter fieldWriter3 = classWriter0.firstField;
      fieldWriter3.getSize();
      ByteVector byteVector0 = new ByteVector(330);
      byteVector0.putShort(330);
      fieldWriter2.put(byteVector0);
      ByteVector byteVector1 = new ByteVector();
      byteVector0.putByte(8);
      fieldWriter0.put(byteVector0);
      assertNotSame(byteVector0, byteVector1);
  }
}
