/*
 * This file was automatically generated by EvoSuite
 * Fri Aug 24 15:10:24 GMT 2018
 */

package com.lts.io;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.lts.io.ArchiveScanner;
import com.lts.io.DirectoryScanner;
import com.lts.io.ImprovedFile;
import java.io.File;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.System;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ArchiveScanner_ESTest extends ArchiveScanner_ESTest_scaffolding {

  /**
  //Test case number: 0
  /*Coverage entropy=1.0986122886681096
  */
  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ImprovedFile improvedFile0 = new ImprovedFile("");
      ImprovedFile improvedFile1 = new ImprovedFile(improvedFile0, ",jZ");
      ArchiveScanner archiveScanner0 = new ArchiveScanner(improvedFile0);
      ImprovedFile.createTempFileName("M`@66mi3bGc,5GMS", "M`@66mi3bGc,5GMS", improvedFile0);
      File file0 = archiveScanner0.basedir;
      improvedFile1.createTempDir();
      ArchiveScanner archiveScanner1 = new ArchiveScanner(improvedFile1);
      ImprovedFile improvedFile2 = new ImprovedFile("", ",jZ");
      int int0 = archiveScanner0.toFileType(improvedFile2);
      assertEquals(0, int0);
  }

  /**
  //Test case number: 1
  /*Coverage entropy=0.6931471805599453
  */
  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ImprovedFile improvedFile0 = null;
      ArchiveScanner archiveScanner0 = new ArchiveScanner((ImprovedFile) null);
      String[] stringArray0 = new String[9];
      stringArray0[0] = "`)Q9k_#fA4y)C4qg6~,";
      stringArray0[1] = "Asked to copy file that is neither directory nor regular file, ";
      stringArray0[2] = "Bak2n}";
      stringArray0[3] = ".war";
      stringArray0[4] = "2iYl";
      stringArray0[5] = "7U?";
      stringArray0[6] = "com.lts.application.Application";
      stringArray0[7] = "m^";
      stringArray0[8] = "H}` R W;1>qWJy#zO#F";
      archiveScanner0.includes = stringArray0;
      archiveScanner0.setBasedir((File) null);
      // Undeclared exception!
      try { 
        archiveScanner0.processArchive((File) null, ", could not delete temp file to make way for directory.");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.lts.io.ArchiveScanner", e);
      }
  }

  /**
  //Test case number: 2
  /*Coverage entropy=1.6094379124341005
  */
  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FileSystemHandling fileSystemHandling0 = new FileSystemHandling();
      ArchiveScanner archiveScanner0 = new ArchiveScanner((ImprovedFile) null);
      ArchiveScanner archiveScanner1 = new ArchiveScanner((ImprovedFile) null);
      File file0 = ImprovedFile.createTempFileName("Error trying to remove archive staging directory, ", "Error trying to remove archive staging directory, ", (File) null);
      ImprovedFile improvedFile0 = new ImprovedFile("ZW:(Fca(4laLoFzeC", "ZW:(Fca(4laLoFzeC");
      ImprovedFile improvedFile1 = improvedFile0.createTempDir();
      ArchiveScanner archiveScanner2 = new ArchiveScanner((ImprovedFile) null);
      ImprovedFile improvedFile2 = new ImprovedFile("VF)bO^$M>8,P[8fDV", "dir0");
      ArchiveScanner archiveScanner3 = new ArchiveScanner(improvedFile0);
      archiveScanner3.toFileType(file0);
      archiveScanner3.filesNotIncluded = null;
      String[] stringArray0 = new String[2];
      stringArray0[0] = "Error trying to remove archive staging directory, ";
      stringArray0[1] = "dir0";
      archiveScanner3.setIncludes(stringArray0);
      archiveScanner1.scandir(improvedFile1, "Error trying to remove archive staging directory, ", true);
      // Undeclared exception!
      try { 
        archiveScanner3.processFile("Error trying to remove archive staging directory, ");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.lts.io.DirectoryScanner", e);
      }
  }

  /**
  //Test case number: 3
  /*Coverage entropy=0.8855741515766717
  */
  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ArchiveScanner archiveScanner0 = new ArchiveScanner((ImprovedFile) null);
      archiveScanner0.includes = archiveScanner0.DEFAULT_ARCHIVE_EXTENSIONS;
      ImprovedFile improvedFile0 = new ImprovedFile(".war", "Could not create temporary directory for archive: ");
      ImprovedFile improvedFile1 = improvedFile0.createTempDir();
      ArchiveScanner archiveScanner1 = new ArchiveScanner(improvedFile0);
      String string0 = "IO error scanning directory ";
      ImprovedFile improvedFile2 = new ImprovedFile("==$", "IO error scanning directory ");
      ArchiveScanner archiveScanner2 = new ArchiveScanner(improvedFile1);
      archiveScanner0.toFileType(improvedFile0);
      improvedFile0.setLastModified(1);
      archiveScanner2.basedir = (File) improvedFile0;
      archiveScanner0.setIncludes(archiveScanner2.DEFAULT_ARCHIVE_EXTENSIONS);
      archiveScanner2.scan();
      try { 
        archiveScanner1.scandir(improvedFile2, ".war", false);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // IO error scanning directory /home/ubuntu/ext1/evosuite_readability_gen/projects/78_caloriecount/==$/IO error scanning directory 
         //
         verifyException("com.lts.io.ArchiveScanner", e);
      }
  }

  /**
  //Test case number: 4
  /*Coverage entropy=1.0751393240053733
  */
  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ImprovedFile improvedFile0 = new ImprovedFile(".war", "Could not crate temprary directory for archive ");
      ImprovedFile improvedFile1 = improvedFile0.createTempDir(".war", ".war");
      ImprovedFile improvedFile2 = new ImprovedFile("IO error scanning directory ");
      ArchiveScanner archiveScanner0 = new ArchiveScanner(improvedFile1);
      DirectoryScanner.match(".war", "Could not crate temprary directory for archive ");
      archiveScanner0.basedir = (File) improvedFile0;
      archiveScanner0.scan();
      improvedFile0.deleteOnExit();
      archiveScanner0.getExcludedDirectories();
      archiveScanner0.scandir(improvedFile0, "child, ", false);
      assertEquals(1392409281320L, improvedFile0.lastModified());
  }

  /**
  //Test case number: 5
  /*Coverage entropy=0.6365141682948128
  */
  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ImprovedFile improvedFile0 = null;
      ArchiveScanner archiveScanner0 = new ArchiveScanner((ImprovedFile) null);
      archiveScanner0.includes = archiveScanner0.DEFAULT_ARCHIVE_EXTENSIONS;
      String[] stringArray0 = new String[7];
      stringArray0[0] = ".war";
      stringArray0[1] = ".war";
      stringArray0[2] = ".war";
      stringArray0[3] = ".war";
      stringArray0[4] = ".war";
      stringArray0[5] = ".war";
      stringArray0[6] = ".war";
      archiveScanner0.excludes = stringArray0;
      // Undeclared exception!
      try { 
        archiveScanner0.processArchive((File) null, ".war");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.lts.io.ArchiveScanner", e);
      }
  }

  /**
  //Test case number: 6
  /*Coverage entropy=1.6715308017791348
  */
  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      String string0 = ".war";
      ImprovedFile improvedFile0 = new ImprovedFile(".war", "Could not crate temprary directory for archive ");
      ImprovedFile improvedFile1 = improvedFile0.createTempDir();
      ArchiveScanner archiveScanner0 = new ArchiveScanner(improvedFile1);
      improvedFile0.setLastModified(1);
      archiveScanner0.basedir = (File) improvedFile0;
      archiveScanner0.scan();
      archiveScanner0.getExcludedDirectories();
      archiveScanner0.processFile("IO error scanning directory ");
      ImprovedFile improvedFile2 = new ImprovedFile(archiveScanner0.basedir);
      try { 
        archiveScanner0.processArchive(improvedFile1, "IO error scanning directory ");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Error trying to list archive, /home/ubuntu/ext1/evosuite_readability_gen/projects/78_caloriecount/.war/Could not crate temprary directory for archive /tempdir0
         //
         verifyException("com.lts.io.archive.AbstractNestedArchive", e);
      }
  }

  /**
  //Test case number: 7
  /*Coverage entropy=1.2342678660790767
  */
  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      ImprovedFile improvedFile0 = new ImprovedFile(".war", "Could not crate temprary directory for archive ");
      ImprovedFile improvedFile1 = improvedFile0.createTempDir();
      ArchiveScanner archiveScanner0 = new ArchiveScanner(improvedFile1);
      String[] stringArray0 = new String[0];
      archiveScanner0.setIncludes(stringArray0);
      FileSystemHandling.appendDataToFile((EvoSuiteFile) null, (byte[]) null);
      improvedFile0.setLastModified(1);
      archiveScanner0.basedir = (File) improvedFile0;
      archiveScanner0.scan();
      archiveScanner0.getExcludedDirectories();
      archiveScanner0.processFile(".war");
      assertEquals(2, ArchiveScanner.ARCHIVE);
  }
}
